server:
  port: 8004

spring:
  application:
    name: msvc-users

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/ecommerce_myshop
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initializationFailTimeout: 0
      connectionTimeout: 30000
      maximumPoolSize: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://msvc-eureka.inventario-ms.local:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always