server:
  port: 8002

spring:
  application:
    name: msvc-orders

  datasource:
    url: jdbc:mysql://
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initializationFailTimeout: 0
      connectionTimeout: 30000
      maximumPoolSize: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost



management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always