server:
  port: 8761

spring:
  application:
    name: msvc-eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://msvc-eureka.inventario-ms.local:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: msvc-eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always